version: '3'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount current directory for live reloading
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    depends_on:
      - fastapi
